plugin_repo(
  name = "go",
  revision = "v1.22.0",
  plugin = "go-rules",
  owner = "please-build",
)

plugin_repo(
  name = "proto",
  revision = "v0.4.0",
  plugin = "proto-rules",
  owner = "please-build",
)

plugin_repo(
  name = "go_proto",
  revision = "v0.3.0",
  plugin = "go-proto-rules",
  owner = "please-build",
)
